---
title: "Estimated P/M"
author: "Sean Kerr"
date: "2023-11-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Plus/Minus
  - Point differential for time a player was on the court vs the time that they were not

Estimated plus/minus
  - HIGHEST above epm

Ideally we train the model on a dataset that looks like

P/M | POINTS | REBS | ASTS | STLS | BLOCKS | TS% | TOV | REST.OF.TEAM.PTS | OTHER.TEAM.PTS

regressed on P/M according 
```{r}
library(tidyverse)
library(regclass)

box <- read.csv('data/ADVANCED_DATA/basic.csv')


total_team_pts <- box %>% group_by(gameid, team) %>% summarize(team_pts = sum(PTS)) %>% group_by(gameid) %>% summarize(max_pts = max(team_pts), min_pts = min(team_pts))

ind_team_pts <- box %>% group_by(gameid, team) %>% summarize(team_pts = sum(PTS))

full_dat <- box %>% 
  left_join(ind_team_pts, by=c('gameid'='gameid', 'team'='team')) %>%
  left_join(total_team_pts, by=c('gameid'='gameid')) %>%
  mutate(other_team_pts = ifelse(team_pts == max_pts, min_pts, max_pts)) %>%
  select(-c(max_pts, min_pts)) %>%
  mutate(team_pts = team_pts - PTS) %>%
  select(-c(home, gameid, team, playerid)) %>%
  na.omit()



mod <- lm(plusminusPTS ~ . - FGM - TRB - PTS - FTM - X3PA, full_dat)

summary(mod)



VIF(mod)


mod_b <- regsubsets(plusminusPTS ~., full_dat, nvmax = 15, method='seqrep')

sum <- summary(mod_b)

ind <- which.max(sum$adjr2)

coef(mod_b, ind)

mod_fin <- lm(plusminusPTS ~ SEC + X3PM + X3PA + FTA + FTpct + ORB + AST + STL + BLK + TOV + PF + team_pts + other_team_pts + TRB + PTS, full_dat)

mod_test <- lm(plusminusPTS ~ SEC + PTS + TRB + AST + other_team_pts + team_pts + TOV, full_dat)

full_dat %>% mutate(exp_pm = predict(mod_test)) %>% mutate(diff = plusminusPTS - exp_pm) %>% group_by(name) %>% summarize(sum_above_expected = sum(diff), n = n()) %>% mutate(above_exp_pg = sum_above_expected / n) %>% filter(n > 60) %>% arrange(-above_exp_pg)
```