---
title: "FG% By Distance"
author: "Sean Kerr"
date: "2023-06-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(hoopR)
pbp <- load_nba_pbp(seasons = most_recent_nba_season()) %>% filter(away_team_name != 'Team Giannis' & home_team_name != 'Team LeBron')  %>% left_join(players_, by = c('athlete_id_1'='athlete_id'))

shooting_plays <- pbp %>% filter(shooting_play==TRUE) %>% mutate(   dist = round(sqrt( ( coordinate_x_raw - 25)^2 + (coordinate_y_raw - 0)^2  )    ), 2) %>% filter(!type_text %in% free_throws)

players_by_dist <- shooting_plays %>% mutate(dist_fac = cut(dist, breaks = c(-5, 0, 5, 10, 15, 20, 25, 30, 35, 40, 500))) %>% group_by(athlete_display_name, dist_fac) %>% summarize(fg_pct = round(mean(scoring_play), 3), n = n())

best_players_by_dist <- players_by_dist %>% filter(n>200) %>% group_by(dist_fac) %>% summarize(fg_pct = max(fg_pct)) %>% left_join(players_by_dist %>% filter(n>200), by=c('fg_pct'='fg_pct')) %>% select(dist_fac.x, fg_pct, n, athlete_display_name) %>% mutate(fg_pct=round(fg_pct, 3))

players_by_dist_wide <- players_by_dist %>% select(-n) %>% pivot_wider(names_from=dist_fac, values_from=fg_pct) %>% group_by(athlete_display_name) %>% summarize(`(0,5]`= max(`(0,5]`),  `(5,10]`= max(`(5,10]`),  `(10,15]`= max(`(10,15]`), `(15,20]`= max(`(15,20]`), `(20,25]`= max(`(20,25]`), `(25,30]`= max(`(25,30]`)) 
```

