---
title: "Player Profiles"
author: "Sean Kerr"
date: "2023-06-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(hoopR)
library(tidyverse)
library(sportyR)
library(gt)
library(ggpmisc)

box <- read_csv('data/box.csv')
pbp <- read_csv('data/pbp.csv')
players_ <- read_csv('data/players_.csv')
hewe <- read_csv('data/height-weight.csv')

court <- geom_basketball('nba', display_range = 'defense', x_trans = 41, y_trans = 25, color_updates = list(plot_background = 'white', court_apron = 'white', two_point_range = 'white', defensive_half_court = 'white', painted_area = 'white', center_circle_fill = 'white', free_throw_circle_fill = 'white', substitution_line='white'))




```

```{r}
pm <- function(stat, minutes){
  round(sum(stat) / sum(minutes), 2)
  
}


create_profile <- function(name){
  he = hewe %>% filter(Player == name) %>% pull(Height)
  we = hewe %>% filter(Player == name) %>% pull(Weight)
  team = players_ %>% filter(athlete_display_name==name) %>% pull(team_name)
  pos = players_ %>% filter(athlete_display_name==name) %>% pull(athlete_position_abbreviation)
  
  overview = gt(data.frame(Team = c(team), Pos = c(pos), Height = c(he), Weight = c(we))) %>% tab_header('Overview', subtitle=name)
  
  pm = box %>% group_by(athlete_display_name) %>% summarize(Points = pm(points, minutes), Rebounds = pm(rebounds, minutes), Assists = pm(assists, minutes), Steals = pm(steals, minutes), Blocks = pm(blocks, minutes)) %>% mutate(Points_Percentile = cume_dist(Points), Rebounds_Percentile = cume_dist(Rebounds), Assists_Percentile = cume_dist(Assists), Steals_Percentile = cume_dist(Steals), Blocks_Percentile = cume_dist(Blocks)) %>% filter(athlete_display_name==name) %>% select(-athlete_display_name) %>% pivot_longer(cols = c(Points, Rebounds, Assists, Steals, Blocks), names_to = 'stat')
    
    #pivot_longer(cols=c(Points_Percentile, Rebounds_Percentile, Assists_Percentile, Steals_Percentile, Blocks_Percentile), names_to = 'percentile')
  
  return(pm)
  

}


all <- box %>% group_by(athlete_display_name) %>% summarize(Points = pm(points, minutes), Rebounds = pm(rebounds, minutes), Assists = pm(assists, minutes), Steals = pm(steals, minutes), Blocks = pm(blocks, minutes)) %>% mutate(Points_Percentile = cume_dist(Points), Rebounds_Percentile = cume_dist(Rebounds), Assists_Percentile = cume_dist(Assists), Steals_Percentile = cume_dist(Steals), Blocks_Percentile = cume_dist(Blocks)) %>% filter(athlete_display_name=='Stephen Curry') %>% select(-athlete_display_name)

all_pm <- c(all$Points, all$Rebounds, all$Assists, all$Steals, all$Blocks)

all_per <- c(round(all$Points_Percentile, 2), round(all$Rebounds_Percentile, 2), round(all$Assists_Percentile, 2),  round(all$Steals_Percentile, 2), round(all$Blocks_Percentile, 2))

stats = c('Points', 'Rebounds', 'Assists', 'Steals', 'Blocks')

pm_fin <- data.frame('Stat' = stats, 'Per Minute' = all_pm, 'Percentile' = all_per * 100) %>% mutate(grade = cut(Percentile, breaks = c(0, 59.9, 62.9, 66.9, 69.9, 72.9, 76.9, 79.9, 82.9, 86.9, 92.9, 96.9, 100))) , labels = c('F', 'D-', 'D', 'D+', 'C-', 'C', 'C+', 'B-', 'B', 'B+', 'A-', 'A', 'A+')))
#ppg <- box %>% group_by(athlete_display_name) %>% summarize(ppg = mean(points)) %>% select(ppg)

#ppg %>% mutate(per = cume_dist(ppg)) %>% arrange(-ppg)

help(cut)
cut(1:20, breaks=c(0, 10, 35), labels = c('low', 'high'))
create_profile('Stephen Curry')
```
